server:
  port: 9090
  
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
      - id: ORDER-SEVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/order/**
        filters:
        - name: CircuitBreaker
          args:
            name: ORDER-SERVICE
            fallbackuri: farward:/orderServiceFallBack
      
      - id: PRODUCT-SEVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/product/**
        filters:
        - name: CircuitBreaker
          args:
            name: PRODUCT-SERVICE
            fallbackuri: farward:/productServiceFallBack
      
      - id: PAYMENT-SEVICE
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment/**
        filters:
        - name: CircuitBreaker
          args:
            name: PAYMENT-SERVICE
            fallbackuri: farward:/paymentServiceFallBack