server:
  port: 9090
  
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
      - id: ORDER-SEVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/order/**
      - id: PRODUCT-SEVICE
        uri: lb://PRODUCT-SERVICE
        predicates:
        - Path=/product/**
      - id: PAYMENT-SEVICE
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment/**